[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacksConfig]
phases.setup = "php81, nginx, libmysqlclient, php81Packages.composer"
phases.install = "composer install --no-dev --optimize-autoloader"
phases.build = "php spark key:generate --force && php spark cache:clear"

[variables]
CI_ENVIRONMENT = "production"
APP_TIMEZONE = "Asia/Jakarta"