[build]
builder = "nixpacks"

[deploy]
startCommand = "php -d memory_limit=512M -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.nixpacksConfig]
phases.setup = "php81, nginx, libmysqlclient, php81Packages.composer"
phases.install = "composer install --no-dev --optimize-autoloader"

[variables]
CI_ENVIRONMENT = "production"
PHP_MEMORY_LIMIT = "512M"